/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTopicsRouteImport } from './routes/_authenticated/topics'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedNewChannelsRouteImport } from './routes/_authenticated/new-channels'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDigestsRouteImport } from './routes/_authenticated/digests'
import { Route as AuthenticatedCommentsRouteImport } from './routes/_authenticated/comments'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedTopicsIdRouteImport } from './routes/_authenticated/topics.$id'
import { Route as AuthenticatedMaterialsIdRouteImport } from './routes/_authenticated/materials.$id'
import { Route as ApiPublicSyncYoutubeRouteImport } from './routes/api/public/sync/youtube'
import { Route as ApiPublicReviewIdRouteImport } from './routes/api/public/review/$id'
import { Route as ApiPublicHooksYoutubePlaylistRouteImport } from './routes/api/public/hooks/youtube-playlist'
import { Route as ApiPublicHooksYoutubeChannelsRouteImport } from './routes/api/public/hooks/youtube-channels'
import { Route as ApiPublicHooksWeeklyDigestRouteImport } from './routes/api/public/hooks/weekly-digest'
import { Route as ApiPublicHooksWatchlistRouteImport } from './routes/api/public/hooks/watchlist'
import { Route as ApiPublicHooksTelegramDigestRouteImport } from './routes/api/public/hooks/telegram-digest'
import { Route as ApiPublicHooksDailyRefreshRouteImport } from './routes/api/public/hooks/daily-refresh'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicsRoute = AuthenticatedTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewChannelsRoute =
  AuthenticatedNewChannelsRouteImport.update({
    id: '/new-channels',
    path: '/new-channels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDigestsRoute = AuthenticatedDigestsRouteImport.update({
  id: '/digests',
  path: '/digests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommentsRoute = AuthenticatedCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicsIdRoute = AuthenticatedTopicsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTopicsRoute,
} as any)
const AuthenticatedMaterialsIdRoute =
  AuthenticatedMaterialsIdRouteImport.update({
    id: '/materials/$id',
    path: '/materials/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSyncYoutubeRoute = ApiPublicSyncYoutubeRouteImport.update({
  id: '/api/public/sync/youtube',
  path: '/api/public/sync/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReviewIdRoute = ApiPublicReviewIdRouteImport.update({
  id: '/api/public/review/$id',
  path: '/api/public/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksYoutubePlaylistRoute =
  ApiPublicHooksYoutubePlaylistRouteImport.update({
    id: '/api/public/hooks/youtube-playlist',
    path: '/api/public/hooks/youtube-playlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksYoutubeChannelsRoute =
  ApiPublicHooksYoutubeChannelsRouteImport.update({
    id: '/api/public/hooks/youtube-channels',
    path: '/api/public/hooks/youtube-channels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyDigestRoute =
  ApiPublicHooksWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/weekly-digest',
    path: '/api/public/hooks/weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWatchlistRoute = ApiPublicHooksWatchlistRouteImport.update({
  id: '/api/public/hooks/watchlist',
  path: '/api/public/hooks/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTelegramDigestRoute =
  ApiPublicHooksTelegramDigestRouteImport.update({
    id: '/api/public/hooks/telegram-digest',
    path: '/api/public/hooks/telegram-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRefreshRoute =
  ApiPublicHooksDailyRefreshRouteImport.update({
    id: '/api/public/hooks/daily-refresh',
    path: '/api/public/hooks/daily-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/digests': typeof AuthenticatedDigestsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/new-channels': typeof AuthenticatedNewChannelsRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/topics': typeof AuthenticatedTopicsRouteWithChildren
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/topics/$id': typeof AuthenticatedTopicsIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-refresh': typeof ApiPublicHooksDailyRefreshRoute
  '/api/public/hooks/telegram-digest': typeof ApiPublicHooksTelegramDigestRoute
  '/api/public/hooks/watchlist': typeof ApiPublicHooksWatchlistRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/api/public/hooks/youtube-channels': typeof ApiPublicHooksYoutubeChannelsRoute
  '/api/public/hooks/youtube-playlist': typeof ApiPublicHooksYoutubePlaylistRoute
  '/api/public/review/$id': typeof ApiPublicReviewIdRoute
  '/api/public/sync/youtube': typeof ApiPublicSyncYoutubeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/digests': typeof AuthenticatedDigestsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/new-channels': typeof AuthenticatedNewChannelsRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/topics': typeof AuthenticatedTopicsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/topics/$id': typeof AuthenticatedTopicsIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-refresh': typeof ApiPublicHooksDailyRefreshRoute
  '/api/public/hooks/telegram-digest': typeof ApiPublicHooksTelegramDigestRoute
  '/api/public/hooks/watchlist': typeof ApiPublicHooksWatchlistRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/api/public/hooks/youtube-channels': typeof ApiPublicHooksYoutubeChannelsRoute
  '/api/public/hooks/youtube-playlist': typeof ApiPublicHooksYoutubePlaylistRoute
  '/api/public/review/$id': typeof ApiPublicReviewIdRoute
  '/api/public/sync/youtube': typeof ApiPublicSyncYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/comments': typeof AuthenticatedCommentsRoute
  '/_authenticated/digests': typeof AuthenticatedDigestsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/new-channels': typeof AuthenticatedNewChannelsRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/topics': typeof AuthenticatedTopicsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/_authenticated/topics/$id': typeof AuthenticatedTopicsIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-refresh': typeof ApiPublicHooksDailyRefreshRoute
  '/api/public/hooks/telegram-digest': typeof ApiPublicHooksTelegramDigestRoute
  '/api/public/hooks/watchlist': typeof ApiPublicHooksWatchlistRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/api/public/hooks/youtube-channels': typeof ApiPublicHooksYoutubeChannelsRoute
  '/api/public/hooks/youtube-playlist': typeof ApiPublicHooksYoutubePlaylistRoute
  '/api/public/review/$id': typeof ApiPublicReviewIdRoute
  '/api/public/sync/youtube': typeof ApiPublicSyncYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/channels'
    | '/comments'
    | '/digests'
    | '/integrations'
    | '/kanban'
    | '/knowledge'
    | '/new-channels'
    | '/radar'
    | '/roles'
    | '/saved'
    | '/topics'
    | '/materials/$id'
    | '/topics/$id'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-refresh'
    | '/api/public/hooks/telegram-digest'
    | '/api/public/hooks/watchlist'
    | '/api/public/hooks/weekly-digest'
    | '/api/public/hooks/youtube-channels'
    | '/api/public/hooks/youtube-playlist'
    | '/api/public/review/$id'
    | '/api/public/sync/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/channels'
    | '/comments'
    | '/digests'
    | '/integrations'
    | '/kanban'
    | '/knowledge'
    | '/new-channels'
    | '/radar'
    | '/roles'
    | '/saved'
    | '/topics'
    | '/'
    | '/materials/$id'
    | '/topics/$id'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-refresh'
    | '/api/public/hooks/telegram-digest'
    | '/api/public/hooks/watchlist'
    | '/api/public/hooks/weekly-digest'
    | '/api/public/hooks/youtube-channels'
    | '/api/public/hooks/youtube-playlist'
    | '/api/public/review/$id'
    | '/api/public/sync/youtube'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/channels'
    | '/_authenticated/comments'
    | '/_authenticated/digests'
    | '/_authenticated/integrations'
    | '/_authenticated/kanban'
    | '/_authenticated/knowledge'
    | '/_authenticated/new-channels'
    | '/_authenticated/radar'
    | '/_authenticated/roles'
    | '/_authenticated/saved'
    | '/_authenticated/topics'
    | '/_authenticated/'
    | '/_authenticated/materials/$id'
    | '/_authenticated/topics/$id'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-refresh'
    | '/api/public/hooks/telegram-digest'
    | '/api/public/hooks/watchlist'
    | '/api/public/hooks/weekly-digest'
    | '/api/public/hooks/youtube-channels'
    | '/api/public/hooks/youtube-playlist'
    | '/api/public/review/$id'
    | '/api/public/sync/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicHooksDailyRefreshRoute: typeof ApiPublicHooksDailyRefreshRoute
  ApiPublicHooksTelegramDigestRoute: typeof ApiPublicHooksTelegramDigestRoute
  ApiPublicHooksWatchlistRoute: typeof ApiPublicHooksWatchlistRoute
  ApiPublicHooksWeeklyDigestRoute: typeof ApiPublicHooksWeeklyDigestRoute
  ApiPublicHooksYoutubeChannelsRoute: typeof ApiPublicHooksYoutubeChannelsRoute
  ApiPublicHooksYoutubePlaylistRoute: typeof ApiPublicHooksYoutubePlaylistRoute
  ApiPublicReviewIdRoute: typeof ApiPublicReviewIdRoute
  ApiPublicSyncYoutubeRoute: typeof ApiPublicSyncYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics': {
      id: '/_authenticated/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AuthenticatedTopicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-channels': {
      id: '/_authenticated/new-channels'
      path: '/new-channels'
      fullPath: '/new-channels'
      preLoaderRoute: typeof AuthenticatedNewChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digests': {
      id: '/_authenticated/digests'
      path: '/digests'
      fullPath: '/digests'
      preLoaderRoute: typeof AuthenticatedDigestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comments': {
      id: '/_authenticated/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AuthenticatedCommentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics/$id': {
      id: '/_authenticated/topics/$id'
      path: '/$id'
      fullPath: '/topics/$id'
      preLoaderRoute: typeof AuthenticatedTopicsIdRouteImport
      parentRoute: typeof AuthenticatedTopicsRoute
    }
    '/_authenticated/materials/$id': {
      id: '/_authenticated/materials/$id'
      path: '/materials/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof AuthenticatedMaterialsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sync/youtube': {
      id: '/api/public/sync/youtube'
      path: '/api/public/sync/youtube'
      fullPath: '/api/public/sync/youtube'
      preLoaderRoute: typeof ApiPublicSyncYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/review/$id': {
      id: '/api/public/review/$id'
      path: '/api/public/review/$id'
      fullPath: '/api/public/review/$id'
      preLoaderRoute: typeof ApiPublicReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/youtube-playlist': {
      id: '/api/public/hooks/youtube-playlist'
      path: '/api/public/hooks/youtube-playlist'
      fullPath: '/api/public/hooks/youtube-playlist'
      preLoaderRoute: typeof ApiPublicHooksYoutubePlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/youtube-channels': {
      id: '/api/public/hooks/youtube-channels'
      path: '/api/public/hooks/youtube-channels'
      fullPath: '/api/public/hooks/youtube-channels'
      preLoaderRoute: typeof ApiPublicHooksYoutubeChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-digest': {
      id: '/api/public/hooks/weekly-digest'
      path: '/api/public/hooks/weekly-digest'
      fullPath: '/api/public/hooks/weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/watchlist': {
      id: '/api/public/hooks/watchlist'
      path: '/api/public/hooks/watchlist'
      fullPath: '/api/public/hooks/watchlist'
      preLoaderRoute: typeof ApiPublicHooksWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-digest': {
      id: '/api/public/hooks/telegram-digest'
      path: '/api/public/hooks/telegram-digest'
      fullPath: '/api/public/hooks/telegram-digest'
      preLoaderRoute: typeof ApiPublicHooksTelegramDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-refresh': {
      id: '/api/public/hooks/daily-refresh'
      path: '/api/public/hooks/daily-refresh'
      fullPath: '/api/public/hooks/daily-refresh'
      preLoaderRoute: typeof ApiPublicHooksDailyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTopicsRouteChildren {
  AuthenticatedTopicsIdRoute: typeof AuthenticatedTopicsIdRoute
}

const AuthenticatedTopicsRouteChildren: AuthenticatedTopicsRouteChildren = {
  AuthenticatedTopicsIdRoute: AuthenticatedTopicsIdRoute,
}

const AuthenticatedTopicsRouteWithChildren =
  AuthenticatedTopicsRoute._addFileChildren(AuthenticatedTopicsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedCommentsRoute: typeof AuthenticatedCommentsRoute
  AuthenticatedDigestsRoute: typeof AuthenticatedDigestsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedNewChannelsRoute: typeof AuthenticatedNewChannelsRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedTopicsRoute: typeof AuthenticatedTopicsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMaterialsIdRoute: typeof AuthenticatedMaterialsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedCommentsRoute: AuthenticatedCommentsRoute,
  AuthenticatedDigestsRoute: AuthenticatedDigestsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedNewChannelsRoute: AuthenticatedNewChannelsRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedTopicsRoute: AuthenticatedTopicsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMaterialsIdRoute: AuthenticatedMaterialsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicHooksDailyRefreshRoute: ApiPublicHooksDailyRefreshRoute,
  ApiPublicHooksTelegramDigestRoute: ApiPublicHooksTelegramDigestRoute,
  ApiPublicHooksWatchlistRoute: ApiPublicHooksWatchlistRoute,
  ApiPublicHooksWeeklyDigestRoute: ApiPublicHooksWeeklyDigestRoute,
  ApiPublicHooksYoutubeChannelsRoute: ApiPublicHooksYoutubeChannelsRoute,
  ApiPublicHooksYoutubePlaylistRoute: ApiPublicHooksYoutubePlaylistRoute,
  ApiPublicReviewIdRoute: ApiPublicReviewIdRoute,
  ApiPublicSyncYoutubeRoute: ApiPublicSyncYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
